language: go

go:
  - 1.5.4
  - 1.6.3
  - 1.7.1

before_install:
  - sudo apt-get update -qq > apt-get.out 2>&1  || (cat apt-get.out && exit 1)
  - sudo apt-get install libgmp-dev -qq > apt-get.out 2>&1 || (cat apt-get.out && exit 1)

install:
  - go get -t ./...
  - go get -u github.com/kisielk/errcheck
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u github.com/golang/lint/golint

script:
  - go test -short
  - go vet ./...
  - errcheck ./...
  - goimports -d . | grep . ; test $? -eq 1
  - golint ./... | grep . ; test $? -eq 1
